version: '3.8'

services:

  database:
    image: postgres:latest
    container_name: fzs-db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
    expose:
      - "${PORT_POSTGRES}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      COMPOSE_HTTP_TIMEOUT: ${COMPOSE_HTTP_TIMEOUT}

  backend:
    build:
      context: ./services/back
      args:
        - PORT_BACKEND=${PORT_BACKEND}
    container_name: fzs-backend
    restart: unless-stopped
    volumes:
      - ./contacts:/app/uploads
      - ./content:/app/public
    depends_on:
      - database
    networks:
      - internal
      - proxy
    expose:
      - "${PORT_BACKEND}"
    ports:
      - "${PORT_BACKEND}:${PORT_BACKEND}"
    environment:
        PORT_BACKEND: ${PORT_BACKEND}
        PORT_POSTGRES: ${PORT_POSTGRES}
        PORT_FRONTEND: ${PORT_FRONTEND}
        SECRET_KEY: ${SECRET_KEY}
        SECRET_AUTH: ${SECRET_AUTH}
        SECRET_PWD: ${SECRET_PWD}
        DOMAIN_NAME: ${DOMAIN_NAME}
        URL_FRONTEND: ${URL_FRONTEND}

  frontend:
    build:
      context: ./services/front
      args:
        PORT_FRONTEND: ${PORT_FRONTEND}
    container_name: fzs-frontend
    restart: unless-stopped
    networks:
      - internal
      - proxy
    depends_on:
      - backend
    expose:
      - "${PORT_FRONTEND}"
    environment:
      VITE_PORT_BACKEND: ${PORT_BACKEND}
      VITE_PORT_FRONTEND: ${PORT_FRONTEND}
      VITE_DOMAIN_NAME: ${DOMAIN_NAME}
      VITE_DOMAIN_EMAIL: ${DOMAIN_EMAIL}
      VITE_SERVICE_BACKEND: ${SERVICE_BACKEND}
      VITE_URL_BACKEND: ${URL_BACKEND}
      VITE_PROJECT_NAME: ${PROJECT_NAME}
      VITE_SITE_RIGHTS: ${SITE_RIGHTS}
      VITE_SITE_SHORT_NAME: ${SITE_SHORT_NAME}
      VITE_SITE_PHONE: ${SITE_PHONE}
      VITE_SITE_EMAIL: ${SITE_EMAIL}
      VITE_SITE_LOGO: ${SITE_LOGO}
      VITE_SITE_BANNER: ${SITE_BANNER}

  nginx-proxy:
    container_name: nginx-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./services/nginx/data:/data
      - ./services/nginx/letsencrypt:/etc/letsencrypt

volumes:
  db-data:

networks:
  internal:
    driver: bridge
  proxy:
    driver: bridge